name: Make a refapps release with compiled package archives

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Version tag (without leading 'v')

jobs:
  build-and-release:
    name: Release Sample Apps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Bump root package.json
        run: npm version --no-git-tag-version ${{ inputs.version }}

      - name: Bump package versions
        run: ./scripts/run-script.js -e "npm version ${{ inputs.version }}"

      - name: Install dependencies
        run: npm install

      - name: Add and commit
        run: git add . && git commit -m "Release version ${{ inputs.version }}"

      - name: Build reference apps
        run: npm run build

      - name: Pack reference apps
        run: npm run pack

      - name: Create a release and upload artifacts
        run: >
          gh release create v${{ inputs.version }} --generate-notes
          dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.SCRAMJET_BOT_TOKEN }}
