name: Make a refapps release with compiled package archives

on: pull_request

jobs:
  build-only:
    name: Build refapps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: ( cd scripts && npm install )

      - name: Build sample sequences
        run: ( cd scripts && npm run build )

      - name: Pack sample sequences
        run: ( cd scripts && npm run pack )

      - name: List packages
        run: ls -la dist/
