name: Make a refapps release with compiled package archives

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    name: Build refapps and make a release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build reference apps
        run: yarn build:refapps

      - name: Prefix python packages to prevent name clash
        run: |
          cd python;
          for pkg in *.tar.gz; do
            mv $pkg python-$pkg;
          done
      
      - name: Prefix typescript packages to prevent name clash
        run: |
          cd typescript;
          for pkg in *.tar.gz; do
            mv $pkg typescript-$pkg;
          done
      
      - name: Prefix javascript packages to prevent name clash
        run: |
          cd javascript;
          for pkg in *.tar.gz; do
            mv $pkg javascript-$pkg;
          done

      - name: Create a release and upload artifacts
        run: >
          gh release create ${{ github.ref }}
          javascript/*.tar.gz
          typescript/*.tar.gz
          python/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.SCRAMJET_BOT_TOKEN }}
