name: Make a refapps release with compiled package archives

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    name: Build refapps and make a release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build reference apps
        run: npm run build

      - name: Pack reference apps
        run: npm run pack

      - name: Create a release and upload artifacts
        run: >
          gh release create ${{ github.ref }}
          dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.SCRAMJET_BOT_TOKEN }}
